### ISSUE TITLE
TerminoloGit:  Hierarchien in Codesystemen mit Sushi

### ISSUE THREAD

**Issue by oliver-krauss** [HL7Austria/HL7-AT-FHIR-Core-R4#1]
**Real Submitter**
Nikola Tanjga

**Resource(s)/Profiles incl. Version
HL7 Austria Religion VS

**Links**
https://collab.hl7.at/display/BAL/2021-01-21+TC+FHIR+Call

**Priority**
BLOCKER. 

**Is your feature request related to a problem? Please describe.**
Change the current value sets to the  Religious Affiliation prepared by the TerminologGit Project Team

**Describe the solution you'd like**
Add the two sushi files, change the links and be awesome.

**Describe alternatives you've considered**
See discussion in https://collab.hl7.at/display/BAL/2020-12-17+TC+FHIR+Call

**Additional context**
Also from https://collab.hl7.at/display/BAL/2020-12-17+TC+FHIR+Call

**Comment by Nik-xT** [comment]
[2021-01-28-VS&CS-package.zip](https://github.com/HL7Austria/HL7-AT-FHIR-Core-R4/files/5888900/2021-01-28-VS.CS-package.zip)

**Comment by regelkraut** [comment]
The URLs for both codeSystems and valueSets have to be adapted ot conform with the url scheme of the HL7 AT profiles.

**Comment by oliver-krauss** [comment]
I think this issue can be closed. The fix from the issue is already in the IG

**Comment by regelkraut** [comment]
Correct, I'll close the issue.
