### ISSUE TITLE
Austrian Patient - uses OID for citizenship which is not yet part of the value set

### ISSUE THREAD

**Issue by regelkraut** [HL7Austria/HL7-AT-FHIR-Core-R4#12]
**Real Submitter**
@regelkraut 

**Resource(s)/Profiles incl. Version**
Austrian Patient, STU1

**Links**
https://hl7austria.github.io/r4-core-ballot_2021_01/StructureDefinition-austrian-patient.html#profile
and
https://hl7austria.github.io/r4-core-ballot_2021_01/ValueSet-VS-ELGA-Laendercodes.html

**Priority**
Major

**Describe the bug**
The description of Patient.extension:citizenship.extension:code.value[x].coding.system uses the OID for the citizienship value set as fixed value.
But in the value set itself this OID is not available.

**To Reproduce**
Compare the usage of citizenship in the Austrian Patient profile and the definition of the value set.

**Expected behavior**
The OID shall be part of the value set as well.

**Attachments**
None.

**Additional context**
None.

**Comment by regelkraut** [comment]
**Ballot Info:** Ballot 2021-1, comments nr. 10, 175

**Ballot Weight:** Z-K (approval with comment)

**Proposed Solution from the "Ballot-Leitkreis:"**
The OID will be part of the value set as well.

**Comment by Nik-xT** [comment]
Will be solved with https://github.com/HL7Austria/HL7-AT-FHIR-Core-R4/issues/13 together.
