### ISSUE TITLE
Religion Extension - uses OID for religion which is not yet part of the value set

### ISSUE THREAD

**Issue by regelkraut** [HL7Austria/HL7-AT-FHIR-Core-R4#13]
**Real Submitter**
@regelkraut 

**Resource(s)/Profiles incl. Version**
Extension for religion, STU1

**Links**
https://hl7austria.github.io/r4-core-ballot_2021_01/StructureDefinition-patientReligion.html
and
https://hl7austria.github.io/r4-core-ballot_2021_01/ValueSet-VS-ELGA-ReligiousAffiliation.html

**Priority**
Major

**Describe the bug**
The description of Extension.extension:code.value[x].coding.system uses the OID for the religion value set as fixed value.
But in the value set itself this OID is not available.

**To Reproduce**
Compare the usage of religion in the exentsion and the definition of the value set.

**Expected behavior**
The OID shall be part of the value set as well.

**Attachments**
None.

**Additional context**
None.

**Comment by regelkraut** [comment]
**Ballot Info:** Ballot 2021-1, comments nr. 9, 174

**Ballot Weight:** Z-K (approval with comment)

**Proposed Solution from the "Ballot-Leitkreis:"**
The OID will be part of the value set as well.

**Comment by Nik-xT** [comment]
The OID will be added for CodeSystems and ValueSets by a identifier element similar to 
```
<identifier>
    <use value="official" />
    <system value="urn:oid:2.16.840.1.113883.16.4.3.2.5" />
</identifier>
```
from https://www.hl7.org/fhir/datatypes-examples.html#Identifier
