### ISSUE TITLE
Examples for profiles and extensions

### ISSUE THREAD

**Issue by regelkraut** [HL7Austria/HL7-AT-FHIR-Core-R4#17]
**Real Submitter**
FH Johanneum, Carina Seerainer

**Resource(s)/Profiles incl. Version**
HL7 AT FHIR Core IG STU1

**Links**
https://hl7austria.github.io/r4-core-ballot_2021_01/artifacts.html

**Priority**
Major

**Is your feature request related to a problem? Please describe.**
There is just an example for the Austrian Patient but nothing for the other profiles and extensions.

**Describe the solution you'd like**
Introduce an "example tab" also for the other profiles and extensions.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by regelkraut** [comment]
**Ballot Info:** Ballot 2021-1, comment nr. 84

**Ballot Weight:** Z-K (approval with comment)

**Proposed Solution from the "Ballot-Leitkreis:"**
Wherever its possible examples will be added.

**Comment by oliver-krauss** [comment]
Note: I assigned @dimitrov-alex as he did this implicitly in the PR
