### ISSUE TITLE
Use AustrianAddress for AustrianPatient.contact.address

### ISSUE THREAD

**Issue by gabriel0316** [HL7Austria/HL7-AT-FHIR-Core-R4#2]
**Real Submitter**
Gabriel Kleinoscheg

**Resource(s)/Profiles incl. Version**
AustrianPatient

**Links**
https://hl7austria.github.io/r4-core-ballot_2021_01/StructureDefinition-austrian-patient.html#root

**Priority**
Major

**Is your feature request related to a problem? Please describe.**
`AustrianPatient.address` is of type `AustrianAddress` whereas `AustrianPatient.contact.address` is of type `Address`.

**Describe the solution you'd like**
Use `AustrianAddress` for `AustrianPatient.contact.address` as well.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by regelkraut** [comment]
Motion: @oliver-krauss Second: @Nik-xT 
Use AustrianAddress for AustrianPatient.contact.address as well.

for-against-abstain: 7-0-0
Motion passed!
