### ISSUE TITLE
Move HL7_AT_Template for IG Publisher into separate repository

### ISSUE THREAD

**Issue by oliver-krauss** [HL7Austria/HL7-AT-FHIR-Core-R4#24]
**Real Submitter**
Kleinoscheg Gabriel

**Resource(s)/Profiles incl. Version**
none

**Links**
https://github.com/gabriel0316/hl7at_template

**Priority**
Major

**Is your feature request related to a problem? Please describe.**
   Currently the template can't be used by HL7 AT members in their own IGs / to expand it for their own purposes

**Describe the solution you'd like**
    Move Template to HL7AT Git Repository
    Edit ig.ini files to link to the repo instead of the folder
    Check if Build still works

**Describe alternatives you've considered**
- none

**Additional context**
- none

**Comment by regelkraut** [comment]
Result from the TC FHIR Call on July 15th:
The following sentences shall be added to the template due to requirements by HL7 International:
"_________ _is the registered trademark of Health Level Seven International and the use does not constitute endorsement by HL7._"
"_________ _ist in eingetragenes Warenzeichen von Health Level Seven International und die Verwendung impliziert weder Standardkonformität noch eine Zustimmung durch HL7._"

**Comment by gabriel0316** [comment]
Once the template has been moved to a separate repository, it would be great if we would publish it on [build.fhir.org](http://build.fhir.org/). Thus it could easily be referenced by `id`.

HL7CH did that with their template
* https://github.com/hl7ch/ig-template
* http://build.fhir.org/ig/hl7ch/ig-template/index.html

**Comment by gabriel0316** [comment]
The following might help a lot in order to make the template available on build.fhir.org: https://github.com/FHIR/auto-ig-builder

**Comment by gabriel0316** [comment]
I just managed to publish a simple custom template on my own - see https://build.fhir.org/ig/gabriel0316/ig-template/

The template may now be referenced by gabriel0316.ig.template in the `ig.ini`.

Thus, I strongly recommend to publish the template on build.fhir.org once it has been moved to a separate repository.

**Comment by oliver-krauss** [comment]
@gabriel0316 We are working on the ballot intensively the next few weeks. Feel free to add yourself to https://doodle.com/poll/cbkrruz9knvydw7b  (if you want details feel free to message me via email)

I can create a repo for you in the HL7Austria space and we can extract the HL7 Austria template and adapt the current impl together.

**Comment by oliver-krauss** [comment]
DONE: http://build.fhir.org/ig/HL7Austria/at-fhir-ig-template/

**Comment by oliver-krauss** [comment]
What is left to do:
- [ ]  merge the CSS
- [ ] rewrite THIS repo to use the IG from build.fhir.org

**Comment by oliver-krauss** [comment]
@gabriel0316  and  @aschuler84 
The IG is now working on the build.fhir published IG. However something went horribly wrong, as not even the HL7 Austria logo is shown anymore. I'll leave the rest to you

**Comment by gabriel0316** [comment]
I'm currently working on it.

**Comment by gabriel0316** [comment]
I completely reworked the template. When I tested it locally I could not detect any differences to the old design.

I created a PR: https://github.com/HL7Austria/at-fhir-ig-template/pull/1

**Comment by oliver-krauss** [comment]
Looks good
![image](https://user-images.githubusercontent.com/39376205/143087612-d775abd9-15b9-4a26-9e12-5dc790877e6c.png)

**Comment by oliver-krauss** [comment]
Since the merge had to happen for this to work I would like to ask @aschuler84 to confirm and close this issue if everything is good!
