### ISSUE TITLE
Change narratives in accordance with rendered IG on index page 

### ISSUE THREAD

**Issue by aschuler84** [HL7Austria/HL7-AT-FHIR-Core-R4#37]
**Real Submitter**
@aschuler84 

**Resource(s)/Profiles incl. Version**
does not apply 

**Links**
https://fhir.hl7.at

**Priority**
Minor

**Describe the bug**
The narrative description on https://fhir.hl7.at/ landing page needs to be aligned with the actual rendered IG

**To Reproduce**
Open https://fhir.hl7.at/ and open https://fhir.hl7.at/r4-core-master/index.html - > they are different - also HL7 Trademarks are missing.

**Expected behavior**
Align narrative in https://fhir.hl7.at landing page with rendered IG

**Attachments**
n.a.

**Additional context**
n.a.

**Comment by oliver-krauss** [comment]
I assume you are referring to the text here:
![image](https://user-images.githubusercontent.com/39376205/143588523-14edcd6a-d735-4f58-8c11-050adb619481.png)

**Comment by aschuler84** [comment]
Changed template for index.html on hl7austria.github.io

**Comment by oliver-krauss** [comment]
Note: There is no review branch for this. Well have two reviewrs look over this issue and confirm before closing

**Comment by oliver-krauss** [comment]
Reviewed by @MaxOS825 and @oliver-krauss -> This should be OK now.
