### ISSUE TITLE
Add narrative for Patient Address

### ISSUE THREAD

**Issue by oliver-krauss** [HL7Austria/HL7-AT-FHIR-Core-R4#43]
Based on #16 - Sub Issue

https://fhir.hl7.at/r4-core-main/StructureDefinition-at-core-address.html -> Definition

at least clarify -> address in AT IT system, NOT physical address in Austria.

**Comment by oliver-krauss** [comment]
Also mention AddressAdditionalInformation, e.g. how is the Austrian address different from the core

**Comment by gabriel0316** [comment]
Added description. Please feel free to make changes.

**Comment by oliver-krauss** [comment]
@gabriel0316  not sure if this was already finished (no review label). If it was feel free to close

**Comment by gabriel0316** [comment]
I commited my changes as part of #46 Reinhard and Nik reviewed the content. That's the reason why it was closed, when #46 was finally merged. I will now close this issue.
