### ISSUE TITLE
Mappings - inconsistent notation

### ISSUE THREAD

**Issue by regelkraut** [HL7Austria/HL7-AT-FHIR-Core-R4#5]
**Real Submitter**
@Nik-xT 

**Resource(s)/Profiles incl. Version**
Austrian Patient, STU1

**Links**
https://hl7austria.github.io/r4-core-ballot_2021_01/StructureDefinition-austrian-patient-mappings.html

**Priority**
Minor

**Describe the bug**
The notation of not available values on the mapping page for the Austrian Patient is not consistent -> n/a vs. N/A

**To Reproduce**
see chapter 2.1.6

**Expected behavior**
The notation shall be consistent for the mappings.

**Attachments**
None

**Additional context**
None

**Comment by regelkraut** [comment]
**Ballot Info:** Ballot 2021-1, comment nr. 188

**Ballot Weight:** Z-T (approval - typo)

**Proposed Solution from the "Ballot-Leitkreis:"**
Unfortunately this is a side effect from the external tool IG Publisher.
But we will try to correct the mapping via sushi.

**Comment by oliver-krauss** [comment]
Discussed on Nov 18 -  We will do the proposed solution. If we can't adapt via sushi, we will not fix this.

**Comment by aschuler84** [comment]
Researched this Problem together with @MaxOS825, as it turns out this problem lies within the IG Publisher. As a workaround however we added a post PR python script that fixes all occurrences of N/A with n/a - however we excluded the current ballot branch. -> see fix_naming.py script in hl7austria.github.io for solution.

**Comment by aschuler84** [comment]
I would also suggest to raise an issue in IGPublisher and bring that to their attention - if not already happen ;)

**Comment by oliver-krauss** [comment]
Can confirm that this is fixed now.
