### ISSUE TITLE
Publish HL7 AT FHIR Core IG STU1

### ISSUE THREAD

**Issue by regelkraut** [HL7Austria/HL7-AT-FHIR-Core-R4#56]
**Real Submitter**
@regelkraut 

**Resource(s)/Profiles incl. Version**
HL7 AT FHIR Core IG STU1

**Links**
[https://fhir.hl7.at/r4-core-main/index.html](https://fhir.hl7.at/r4-core-main/index.html)

**Priority**
Major 

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Publish the balloted version of HL7 AT FHIR Core IG STU1.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by aschuler84** [comment]
@regelkraut please verify if done and close.
