### ISSUE TITLE
Mappings - extend CDA mapping for patient identifiers

### ISSUE THREAD

**Issue by regelkraut** [HL7Austria/HL7-AT-FHIR-Core-R4#6]
**Real Submitter**
@Nik-xT 

**Resource(s)/Profiles incl. Version**
Austrian Patient, STU1

**Links**
https://hl7austria.github.io/r4-core-ballot_2021_01/StructureDefinition-austrian-patient-mappings.html#mappings-for-cda-r2-http-hl7-org-v3-cda

**Priority**
Minor

**Is your feature request related to a problem? Please describe.**
The mapping of the Austrian Patient to CDA structures is currently very generic. A further alignement to the Austrian CDA guidelines would be helpful.

**Describe the solution you'd like**
This concerns the mapping of the identifiers of a patient -> social security number, bpk-GH, local patient id.
It should be aligned with the definition of identifiers in the Austrian ELGA CDA guidelines:
* id[1] Identifikation des Patienten im lokalen System (1..1 M)
* id[2] Sozialversicherungsnummer des Patienten (1..1 R)
* id[@root="1.2.40.0.10.2.1.1.149"] Bereichsspezifisches Personenkennzeichen (0..1 O)

**Describe alternatives you've considered**
If extending the mapping isn't possible that easily, maybe the information could be part of a narrative.

**Additional context**
In opposition to FHIR the Austrian ELGA CDA guideline also define an order of the identifiers. Introducing this extended mapping  could facilitate the implementation.

**Comment by regelkraut** [comment]
**Ballot Info:** Ballot 2021-1, comment nr. 189

**Ballot Weight:** Z-V (approval with proposal)

**Proposed Solution from the "Ballot-Leitkreis:"**
We will investigate if it is possible to influence the mapping via sushi and try to implement this feature.

**Comment by regelkraut** [comment]
We will try the following approaches as described here:
https://build.fhir.org/ig/HL7/fhir-shorthand/reference.html#defining-mappings
and here
https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/profiles.20with.20mapping

e.g.
```
Mapping: HL7ATCorePatient2CDA
Source: at-core-patient
Target: "http://hl7.org/v3/cda"
Id: at-core-mapping-patient2cda
Title: "Mappings for CDA (R2)"
* -> "Patient"
* identifier[socialSecurityNumber] -> ".id[1]"
```

**Comment by regelkraut** [comment]
Proposal:
Since the required mapping of this ticket is in fact not based on the international CDA definition itself but on the national CDA guideline of ELGA, we will use this “feature” and introduce a separate mapping chapter 2.1.6.6.
For now, it will only contain the relevant differences in the mapping and not the full structure as in chapter 2.1.6.2.

**Comment by aschuler84** [comment]
Result from the TC FHIR Call on December 16th 2021:
Motion: @Nik-xT  Second: @sabutsch 
- Include all relevant mappings to HL7 Austria "Allgemeiner Leitfaden CDA"
- Mapping serves as a foundation for future Profiles

for-against-abstain: 10-0-0
Motion passed!

**Comment by Nik-xT** [comment]
Mappings added: https://fhir.hl7.at/r4-core-6-extend-cda-mapping/StructureDefinition-at-core-patient-mappings.html
