### ISSUE TITLE
Mappings - introduce mapping for the deceased attribute for CDA

### ISSUE THREAD

**Issue by regelkraut** [HL7Austria/HL7-AT-FHIR-Core-R4#7]
**Real Submitter**
@Nik-xT 

**Resource(s)/Profiles incl. Version**
Austrian Patient, STU1

**Links**
https://hl7austria.github.io/r4-core-ballot_2021_01/StructureDefinition-austrian-patient-mappings.html#mappings-for-cda-r2-http-hl7-org-v3-cda

**Priority**
Minor

**Is your feature request related to a problem? Please describe.**
The mapping of the Austrian Patient to CDA structures is currently very generic. A further alignement to the Austrian CDA guidelines would be helpful.

**Describe the solution you'd like**
With the latest versions of the Austrian ELGA CDA guidelines an information was added if a patient is deceased.
The current CDA mapping for the Austrian Patient lists the attribute deceased as not available.
Introduce a mapping to:
* sdtc:deceasedTime
* sdtc:deceasedInd (boolean)

**Describe alternatives you've considered**
If extending the mapping isn't possible that easily, maybe the information could be part of a narrative.

**Additional context**
The deceased attribute is not part of the official CDA R2 definition. For the Austrian ELGA CDA guideline an HL7 International CDA extension from the Structured Documents Workgroup was used. See https://confluence.hl7.org/display/SD/CDA+Extensions for further information.

**Comment by regelkraut** [comment]
**Ballot Info:** Ballot 2021-1, comment nr. 190

**Ballot Weight:** Z-V (approval with proposal)

**Proposed Solution from the "Ballot-Leitkreis:"**
We will investigate if it is possible to influence the mapping via sushi and try to implement this feature.

**Comment by oliver-krauss** [comment]
Discussed on Nov 18th - will investigate if possible with sushi. If not we will at least add a narrative to the IG.

**Comment by regelkraut** [comment]
This ticket will be resolved together with ticket #6

**Comment by aschuler84** [comment]
See discussion result and motion in #6 - applies for this issue as well.
