### ISSUE TITLE
Change ID of IG

### ISSUE THREAD

**Issue by gabriel0316** [HL7Austria/HL7-AT-FHIR-Core-R4#79]
**Real Submitter**
Gabriel Kleinoscheg

**Resource(s)/Profiles incl. Version**
ImplementationGuide

**Links**
https://github.com/HL7Austria/HL7-AT-FHIR-Core-R4/blob/main/sushi-config.yaml

**Priority**
Minor

**Is your feature request related to a problem? Please describe.**
The ID of the HL7-AT-FHIR-Core-R4 is `HL7ATCoreProfiles`.

**Describe the solution you'd like**
Align the IG's ID with the ID of the [AT Template](https://github.com/HL7Austria/at-fhir-ig-template/blob/master/package/package.json#L2): `hl7.at.fhir.template`. This ID was originally proposed by Grahame Grieve.

So the IG's ID could be something like: `hl7.at.fhir.core` - maybe someone would like to add the FHIR version, e.g. `hl7.at.fhir.r4.core` (the fhir specification e.g. just uses `hl7.fhir.core` but has the version set to 5.0.0 for the FHIR version).

The [CH Core](https://github.com/hl7ch/ch-core/blob/master/sushi-config.yaml#L1) follows a similar pattern:  `ch.fhir.ig.ch-core`

**Comment by regelkraut** [comment]
> The current id of the implementation guide is also part of the canonical url of each artifact. @gabriel0316 should we adjust the canonicals as well (and therefore cause a lot of breaking changes) or is the adaption of the IG id itself enough?

We decided to not touch the canonical url and just adapt the id itself.

**Comment by regelkraut** [comment]
Discussion about the id structure:
https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/national.20base.20IG.20id
