### ISSUE TITLE
Copyright information for HL7 & FHIR on the IG home page

### ISSUE THREAD

**Issue by regelkraut** [HL7Austria/HL7-AT-FHIR-Core-R4#8]
**Real Submitter**
@regelkraut 

**Resource(s)/Profiles incl. Version**
HL7 AT FHIR Core IG STU1

**Links**
https://hl7austria.github.io/r4-core-ballot_2021_01/index.html

**Priority**
Major

**Describe the bug**
The HL7 International requirement to use the copyright and/or trademark symbol for HL7 & FHIR is not met yet for the HL7 AT FHIR Core IG.

**To Reproduce**
See the IG home page.

**Expected behavior**
Introduce the copyright information for HL7 & FHIR somewhere on the introduction page.

**Attachments**
None

**Additional context**
For best practice - HL7 Switzerland has this information:
* within the FHIR symbol on each page
* in a separate chapter on the IG home page, see http://fhir.ch/ig/ch-core/index.html

**Comment by regelkraut** [comment]
**Ballot Info:** Ballot 2021-1, comment nr. 4

**Ballot Weight:** Z-V (approval with proposal)

**Proposed Solution from the "Ballot-Leitkreis:"**
The copyright and trademark symbols for HL7 & FHIR will be used on the IG home page.

**Comment by regelkraut** [comment]
@aschuler84 I've added a chapter to the IG home page with copyright information.
Can you please adapt the HL7 icons of the hl7-at-template to show copyright symbols as well.

**Comment by regelkraut** [comment]
Walked through the IG together with @aschuler84 - no symbols to adapt could be found.

**Comment by oliver-krauss** [comment]
It may be the case that no symbols to adapt could be found but we are still missing the Section "Licence and Legal Terms" on the homepage as you even outline in your own submission - http://fhir.ch/ig/ch-core/index.html
