### ISSUE TITLE
Rework the introduction chapter

### ISSUE THREAD

**Issue by regelkraut** [HL7Austria/HL7-AT-FHIR-Core-R4#9]
**Real Submitter**
@regelkraut 

**Resource(s)/Profiles incl. Version**
HL7 AT FHIR Core IG STU1

**Links**
https://hl7austria.github.io/r4-core-ballot_2021_01/index.html#introduction

**Priority**
Major

**Describe the bug**
The current description in the introduction chapter does not represent the actual process anymore for FHIR IGs at HL7 Austria. 

**To Reproduce**
see chapter 1.1

**Expected behavior**
Rework the chapter 1.1 to comply with the actual process.

**Attachments**
None.

**Additional context**
None.

**Comment by regelkraut** [comment]
**Ballot Info:** Ballot 2021-1, comments nr. 3, 168

**Ballot Weight:** Z-K (approval with comment)

**Proposed Solution from the "Ballot-Leitkreis:"**
The chapter 1.1 will be updated accordingly.

**Comment by oliver-krauss** [comment]
Old version:
This is a draft for an implementation guide for the HL7 Austria FHIR Core Profiles based on HL7 FHIR R4. It is a “work in progress” implementation guide that is hosted on the HL7 Austria github project will get updated continuously. Ballot versions of this implementation guide will be published via the HL7 Austria homepage.

Recommendation for new Wording:
This is the version X of the implementation guide for the HL7 Austria FHIR Core Profiles based on HL7 FHIR R4. It is a “balloted” implementation guide that is hosted on the HL7 Austria github project. The most recent versionof this implementation guide can be found at fhir.at.

Discussed on Nov 18 FHIR Call

**Comment by oliver-krauss** [comment]
Note: I am combining #8 and #9 on the PR #32 since both touch the Introduction
