### ISSUE TITLE
Alias.fsh Dead Code Removal

### ISSUE THREAD

**Issue by alackerbauer** [HL7Austria/HL7-AT-FHIR-Core-R4#96]
**Real Submitter**
FH OÖ

**Resource(s)/Profiles incl. Version**
n/a

**Links**
https://github.com/HL7Austria/HL7-AT-FHIR-Core-R4/blob/main/input/fsh/Alias.fsh

**Priority**
Minor

**Is your feature request related to a problem? Please describe.**
Outdated aliases still exist in the file as comments

**Describe the solution you'd like**
Remove dead code comments and check other aliases if they are still being used.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by alackerbauer** [comment]
Question: I have identified additional unused code within the FSH files. Should this be considered for removal as well?

- https://github.com/HL7Austria/HL7-AT-FHIR-Core-R4/blob/main/input/fsh/at-core-patient.fsh#L98
- https://github.com/HL7Austria/HL7-AT-FHIR-Core-R4/blob/main/input/fsh/at-core-patient.fsh#L114
- https://github.com/HL7Austria/HL7-AT-FHIR-Core-R4/blob/main/input/fsh/at-core-patient.fsh#L130

**Comment by regelkraut** [comment]
Outcome of the reconciliation meeting on 10.09.2024:
* The reporter of the corresponding ballot comment is ok with this proposal, so let's use this ticket to do some more clean up of dead code
